application: literumble
version: 2-8
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: .UploadedResults
  script: UploadedResults.application

- url: .Rankings
  script: Rankings.application
  
- url: .RatingsFile
  script: RatingsFile.application
  
- url: .RemoveOldParticipant
  script: RemoveOldParticipant.application

- url: .BotDetails
  script: BotDetails.application

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /
  script: RumbleSelect.application
  
- url: .BatchRankings
  script: BatchRankings.application
  login: admin

- url: .BotCompare
  script: BotCompare.application
