application: literumble
version: 3-5
runtime: python27
threadsafe: yes
api_version: 1

libraries:
- name: numpy
  version: "latest"

- name: PIL
  version: "latest"

builtins:
- remote_api: on

error_handlers:
- error_code: over_quota
  file: over_quota.txt

handlers:
- url: .UploadedResults
  script: UploadedResults.application

- url: /flags
  static_dir: flags
  expiration: "99d"

- url: .HandleQueuedResults
  script: HandleQueuedResults.application
  login: admin

- url: .FetchParseFlags
  script: FetchParseFlags.application
  login: admin

- url: .Rankings
  script: Rankings.application
  
- url: .RatingsFile
  script: RatingsFile.application
  
- url: .RemoveOldParticipant
  script: RemoveOldParticipant.application

- url: .BotDetails
  script: BotDetails.application

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "99d"
  
- url: /style.css
  static_files: style.css
  upload: style.css
  expiration: "10d"

- url: /
  script: RumbleSelect.application

- url: .RumbleStats
  script: RumbleStats.application
  
- url: .BatchRankings
  script: BatchRankings.application
  login: admin

- url: .BotCompare
  script: BotCompare.application
