application: literumble
version: 1
runtime: python
api_version: 1

handlers:
- url: .UploadedResults
  script: UploadedResults.py

- url: .Rankings
  script: Rankings.py
  
- url: .RatingsFile
  script: RatingsFile.py
  
- url: .RemoveOldParticipant
  script: RemoveOldParticipant.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
