application: literumble
version: 2-4
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: .UploadedResults
  script: UploadedResults.py

- url: .Rankings
  script: Rankings.py
  
- url: .RatingsFile
  script: RatingsFile.py
  
- url: .RemoveOldParticipant
  script: RemoveOldParticipant.py

- url: .BotDetails
  script: BotDetails.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  script: RumbleSelect.py
